name: Build macOS

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup dependencies
        env:
          HOMEBREW_NO_ANALYTICS: 1
        run: brew install sdl2
      - name: Build irisdual
        run: |
          cmake -Bbuild \
            -DCMAKE_CXX_FLAGS="-s" \
            -DBUILD_STATIC=ON \
            -DCMAKE_BUILD_TYPE=Release
          cd build
          make -j$(getconf _NPROCESSORS_ONLN)
      - name: Fix library paths
        run: |
          install_name_tool -add_rpath "@executable_path" build/bin/sdl/dual
          install_name_tool -change /usr/local/opt/sdl2/lib/libSDL2-2.0.0.dylib "@rpath/libSDL2-2.0.0.dylib" build/bin/sdl/dual
      - name: Create output directory
        run: |
          mkdir dist
          cp build/bin/sdl/dual dist/
          cp /usr/local/opt/sdl2/lib/libSDL2-2.0.0.dylib dist/
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: irisdual-${{ runner.os }}
          path: dist
          if-no-files-found: error
